language: cpp

os:
    - linux
    - osx

compiler:
    - clang++-6
    - g++-7

addons:
  apt:
    packages:
    - cmake
    - libx11-dev libgl1-mesa-dev libglu1-mesa-dev libasound2-dev libgtk2.0-dev xorg-dev

script:
    - cmake . && make && make test

notifications:
  email:
    - skattomaskatto@gmail.com
