language: cpp

matrix:
  include:
    # Linux
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-7
            - cmake
            - libx11-dev libgl1-mesa-dev libglu1-mesa-dev libasound2-dev libgtk2.0-dev xorg-dev
      compiler: clang++-7

    # Mac OS X
    - os: osx
      compiler: clang++

before_install:
    - eval "${MATRIX_EVAL}"

script:
    - mkdir build && cd build
    - cmake .. && make && ./bin/fase_test

notifications:
  email:
    - skattomaskatto@gmail.com
